version: 0.2

phases:
  install:
    commands:
      - echo update npm...
      - npm install -g --force n
      - npm update -g npm
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - ls -la
      - echo Compiling the Node.js code
      - npm run build:development
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Distributing to S3...
artifacts:
  files:
    - "**/*"
  base-directory: build
